/* Auto-generated by genmsg_cpp for file /opt/projects/adler/planetxrobots/ros/DirectionButtons/msg/DirectionButton.msg */
#ifndef DIRECTIONBUTTONS_MESSAGE_DIRECTIONBUTTON_H
#define DIRECTIONBUTTONS_MESSAGE_DIRECTIONBUTTON_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace DirectionButtons
{
template <class ContainerAllocator>
struct DirectionButton_ : public ros::Message
{
  typedef DirectionButton_<ContainerAllocator> Type;

  DirectionButton_()
  : header()
  , buttonEvent()
  {
  }

  DirectionButton_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , buttonEvent(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _buttonEvent_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  buttonEvent;


private:
  static const char* __s_getDataType_() { return "DirectionButtons/DirectionButton"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "9df72beb13d34aac7e6eea37f77e9299"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "#\n\
# the direction (joystick) or button event\n\
#\n\
Header header\n\
string buttonEvent\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, buttonEvent);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, buttonEvent);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(buttonEvent);
    return size;
  }

  typedef boost::shared_ptr< ::DirectionButtons::DirectionButton_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DirectionButtons::DirectionButton_<ContainerAllocator>  const> ConstPtr;
}; // struct DirectionButton
typedef  ::DirectionButtons::DirectionButton_<std::allocator<void> > DirectionButton;

typedef boost::shared_ptr< ::DirectionButtons::DirectionButton> DirectionButtonPtr;
typedef boost::shared_ptr< ::DirectionButtons::DirectionButton const> DirectionButtonConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::DirectionButtons::DirectionButton_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::DirectionButtons::DirectionButton_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace DirectionButtons

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::DirectionButtons::DirectionButton_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9df72beb13d34aac7e6eea37f77e9299";
  }

  static const char* value(const  ::DirectionButtons::DirectionButton_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9df72beb13d34aacULL;
  static const uint64_t static_value2 = 0x7e6eea37f77e9299ULL;
};

template<class ContainerAllocator>
struct DataType< ::DirectionButtons::DirectionButton_<ContainerAllocator> > {
  static const char* value() 
  {
    return "DirectionButtons/DirectionButton";
  }

  static const char* value(const  ::DirectionButtons::DirectionButton_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::DirectionButtons::DirectionButton_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#\n\
# the direction (joystick) or button event\n\
#\n\
Header header\n\
string buttonEvent\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::DirectionButtons::DirectionButton_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::DirectionButtons::DirectionButton_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::DirectionButtons::DirectionButton_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::DirectionButtons::DirectionButton_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.buttonEvent);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DirectionButton_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DirectionButtons::DirectionButton_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::DirectionButtons::DirectionButton_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "buttonEvent: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.buttonEvent);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DIRECTIONBUTTONS_MESSAGE_DIRECTIONBUTTON_H

